core/urls.py
from django.conf.urls import url, include

from .views	import usuario_detalhe, home

urlpatterns = [
   url(r'^home/', home, name='home'),
   url(r'^usuario/', usuario_detalhe, name='usuario'),
]

fiocruz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.urls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^armazem/', include('armazem.urls', namespace='armazem')),
    url(r'^compra/', include('compra.urls', namespace='compra')),
    url(r'^fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    url(r'^item/', include('item.urls', namespace='item')),
    url(r'^requisicao/', include('requisicao.urls', namespace='requisicao')),
    url(r'^usuario/', include('core.urls', namespace='core')),
    url(r'^login/',views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/',views.logout_then_login, { 'login_url': '/login/'}, name='logout')
]

requisicao/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.urls import views

from .views import requisicao_lista, requisicao_cria,requisicao_apaga, requisicao_detalhe, requisicao_listadeitens, requisicaoitem_detalhe, requisicaoitem_apaga, requisicaoitem_edita, requisicaoitem_cria, requisicao_enviar

urlpatterns = [
    url(r'^$', requisicao_lista, name='lista'),
    url(r'^apaga/(?P<id>\d+)/$', requisicao_apaga, name='apaga'),
    url(r'^detalhe/(?P<id>\d+)/$',requisicao_detalhe,name='detalhe'),
    url(r'^cria/$', requisicao_cria, name='cria'),
    url(r'^enviar/(?P<id>\d+)/$', requisicao_enviar, name='enviar'),   
    url(r'^listadeitens/(?P<id>\d+)/$', requisicao_listadeitens, name='listadeitens'),
    url(r'^requisicaoitemapaga/(?P<id>\d+)/$', requisicaoitem_apaga, name='requisicaoitemapaga'),
    url(r'^requisicaoitemcria/(?P<id>\d+)/$', requisicaoitem_cria, name='requisicaoitemcria'),
    url(r'^requisicaoitemdetalhe/(?P<id>\d+)/$', requisicaoitem_detalhe, name='requisicaoitemdetalhe'), 
    url(r'^requisicaoitemedita/(?P<id>\d+)/$', requisicaoitem_edita, name='requisicaoitemedita'),
]

requisicao/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models.signals import pre_save

from item.models import Item

class Requisicao(models.Model):

	situacao	= models.BooleanField(default=False)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)
	usuario	    = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)

	class Meta:
		ordering = ['-atualizado','-criado']
		permissions = (
            ('pode_administrar', 'Pode Administrar'),            
        )
		
	def __unicode__(self):
		return self.id

	def __str__(self):
		return self.id

	def get_absolute_url(self):
		return reverse('requisicao:detalhe', kwargs={'id':self.id})

class RequisicaoItem(models.Model):

	item 		= models.ForeignKey(Item,on_delete=models.PROTECT)
	requisicao  = models.ForeignKey(Requisicao,on_delete=models.PROTECT)
	quantidade	= models.IntegerField(null=False)
	situacao	= models.BooleanField(default=False)								# Atendida True.
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)
	usuario	    = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)

	class Meta:
		ordering = ['-atualizado','-criado']
		permissions = (
            ('pode_administrar', 'Pode Administrar'),            
    )
		
	def __unicode__(self):
		return self.id

	def __str__(self):
		return self.id

	def get_absolute_url(self):
		return reverse('requisicao:requisicaoitemdetalhe', kwargs={'id':self.id})

requisicao/forms.py
from django import forms

from .models import Requisicao
from .models import RequisicaoItem

class RequisicaoForm(forms.ModelForm):
	class Meta:
		model = Requisicao
		fields = {
		}

class RequisicaoItemForm(forms.ModelForm):
	class Meta:
		model = RequisicaoItem
		fields = {
		'item',
		'quantidade',
		}

requisicao/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from .models import Requisicao, RequisicaoItem
from .forms import RequisicaoForm
from .forms import RequisicaoItemForm

@login_required
def requisicao_apaga(request,id=None):
	instance = get_object_or_404(Requisicao,id=id)
	if instance.situacao == True:
		messages.warning(request,' Requisição "%s" está enviada não pode ser apagada.' % id)
		return redirect('requisicao:lista')
	if instance.usuario == request.user:			# Permissões tratar requisições, Verificar Funcao.
		try:
			instance.delete()
			messages.success(request,' Requisição "%s" foi excluida.' % id)
		except IntegrityError:
			messages.warning(request,' A Requisição "%s" não pode ser excluída, devido a vínculo com outra informação.' % instance.id)
	else:
		messages.warning(request,' A Requisição "%s" não pode ser excluída, pois é de propriendade de outro usuario.' % instance.id)
	return redirect('requisicao:lista')

@login_required
def requisicao_enviar(request,id):	
	instance = Requisicao.objects.get(id=id)
	itens = RequisicaoItem.objects.filter(requisicao=instance.id)
	if instance.situacao == True:
		messages.warning(request,' Requisição "%s" já foi enviada uma vez.' % id)
		return redirect('requisicao:lista')
	if instance.usuario == request.user:
		if itens:
			instance.situacao=True
			instance.usuario = request.user
			instance.save()
			messages.warning(request,' Requisição "%s" enviada.' % id)
			return redirect('requisicao:lista')
		else:
			messages.warning(request,' Requisição "%s" não pode ser fechada por não há itens vinculados.' % id)
			return redirect('requisicao:lista')
	else:
		messages.warning(request,' Requisição "%s" pode ser fechada somente pelo usuário proprietário.' % id)
		return redirect('requisicao:lista')

@login_required
def requisicao_cria(request):
	form = RequisicaoForm(request.POST or None)
	instance = form.save(commit=False)
	instance.usuario = request.user
	instance.save()
	messages.success(request,' Requisição "%s" foi criada.' % instance.id)
	return HttpResponseRedirect(instance.get_absolute_url())

@login_required
def requisicao_detalhe(request,id):
	queryset_detalhe = Requisicao.objects.get(id=id)
	if queryset_detalhe.usuario == request.user or request.user.has_perm('requisicao.pode_administrar'):	
		context = { 'requisicao':queryset_detalhe}
		return render(request,'requisicao_detalhe.html', context)
	else:
		messages.warning(request,' A Requisição "%s" não pode ser vista, pois é de propriendade de outro usuario.' % instance.id)
		return redirect('requisicao:lista')

def requisicao_lista(request):
	if request.user.has_perm('requisicao.pode_administrar'):			# Permissões tratar requisições, Verificar Funcao.
		queryset_list = Requisicao.objects.all() 
	else:
		queryset_list = Requisicao.objects.all().filter(usuario=request.user)
	page_request_var='Pagina'
	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(id__icontains=query)
	paginator = Paginator(queryset_list, 8)
	page = request.GET.get(page_request_var)
	try:
		queryset_list = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset_list = paginator.page(paginator.num_pages)
	context = { 'requisicoes':queryset_list,
				'page_request_var':page_request_var 
				}
	return render(request,'requisicao_lista.html', context)

@login_required
def requisicaoitem_apaga(request,id=None):
	instance = get_object_or_404(RequisicaoItem,id=id)
	if instance.requisicao.situacao == True:
		messages.warning(request,' Requisição "%s" está enviada não pode ser apagado seus itens.' % id)
		return redirect('requisicao:listadeitens',instance.requisicao.id)
	if instance.situacao:
		messages.warning(request,' Item da Requisicao foi atendido, não é possível excluir este item.')
		return redirect('requisicao:listadeitens',instance.requisicao.id)
	if instance.usuario == request.user: 
		instance.delete()
		messages.success(request,' Item da Requisicao foi excluida.')
		return redirect('requisicao:listadeitens',instance.requisicao.id)
	else:
		messages.warning(request,' O Item da Requisicao "%s" pode ser excluído somente pelo usuário proprietário do item.' % instance.id)
		return redirect('requisicao:listadeitens',instance.requisicao.id)

@login_required
def requisicaoitem_cria(request,id):
	formItem = RequisicaoItemForm(request.POST or None)
	queryset_requisicao = Requisicao.objects.get(id=id)
	if queryset_requisicao.situacao == True:
		messages.warning(request,' Requisição "%s" está enviada não pode ser adicionado mas itens.' % id)
		return redirect('requisicao:listadeitens',queryset_requisicao.id)
	if queryset_requisicao.usuario != request.user:
		messages.warning(request,' O Item da Requisicao "%s" pode ser criado somente pelo usuário proprietário da requisicao.' % queryset_requisicao.id)
		return redirect('requisicao:listadeitens',queryset_requisicao.id)	
	if formItem.is_valid():
		instance = formItem.save(commit=False)
		instance.requisicao = queryset_requisicao
		instance.usuario = request.user
		instance.save()
		messages.success(request,' Item de Requisicao foi criado.')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = { 'formItem': formItem,
					'requisicao':queryset_requisicao, }
	return render(request,'requsitcaoitem_form.html', context)

@login_required
def requisicaoitem_edita(request,id=None):	
	instance = get_object_or_404(RequisicaoItem,id=id)	
	queryset_requisicao = Requisicao.objects.get(id=instance.requisicao.id)
	if queryset_requisicao.situacao == True:
		messages.warning(request,' Requisição "%s" está enviada não pode ser modificado seus itens.' % id)
		return redirect('requisicao:listadeitens',queryset_requisicao.id)
	if instance.usuario != request.user:
		messages.warning(request,' O Item da Requisicao "%s" pode ser alterado somente pelo usuário proprietário do item.' % instance.id)
		return redirect('requisicao:listadeitens',instance.requisicao.id)		
	form = RequisicaoItemForm(request.POST or None, instance=instance)
	if instance.situacao: 
		messages.warning(request,' Item atendido, não é possivel editar.')
		return redirect('requisicao:listadeitens',instance.requisicao.id)
	else:
		if form.is_valid():
			instance = form.save(commit=False)
			instance.usuario = request.user
			instance.save()
			messages.success(request,' item da Requisicao foi modificado.')
			return HttpResponseRedirect(instance.get_absolute_url())
	context = { 'formItem':form,
				'requisicao':queryset_requisicao,}
	return render(request,'requsitcaoitem_form.html', context)

@login_required
def requisicaoitem_detalhe(request,id):
	queryset_detalhe = RequisicaoItem.objects.get(id=id)
	queryset_requisicao = Requisicao.objects.get(id=queryset_detalhe.requisicao.id)
	if queryset_detalhe.usuario == request.user or request.user.has_perm('requisicao.pode_administrar'):
		context = { 'requisicaoitem':queryset_detalhe,
					'requisicao':queryset_requisicao, }
		return render(request,'requisicaoitem_detalhe.html', context)
	else:
		messages.warning(request,' O Item da Requisição "%s" não pode ser vista, pois é de propriendade de outro usuario.' % queryset_requisicao.id)
		return redirect('requisicao:lista')

@login_required
def requisicao_listadeitens(request,id):
	if request.user.has_perm('requisicao.pode_administrar'):			# Permissões tratar requisições, Verificar Funcao.
		queryset_list = RequisicaoItem.objects.filter(requisicao=id)
	else:
		queryset_list = RequisicaoItem.objects.filter(requisicao=id).filter(usuario=request.user)
	queryset_requisicao = Requisicao.objects.get(id=id)
	# queryset = Armazem.objects.all().order_by('-criado,-atualizado') 
	page_request_var='Pagina'
	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(requisicao__id__icontains=query)
	paginator = Paginator(queryset_list, 8)
	page = request.GET.get(page_request_var)
	try:
		queryset_list = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset_list = paginator.page(paginator.num_pages)
	context = { 'listadeitens':queryset_list,
				'requisicao': queryset_requisicao,
				'page_request_var':page_request_var 
				}
	return render(request,'requisicao_listadeitens.html', context)

requisicao/templates/requisicao_detalhe.html
{% extends 'base.html' %}

{% block header %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-4">
        <h4>Materiais: Requisicao - Detalhe</h4>
    </div>   
    <div class="col-sm-5">
    </div>   
    <form>
        <div class="col-sm-1 text-right">
            <button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="{{ requisicao.get_absolute_url }}">
            <span class="glyphicon glyphicon-refresh"></span></button>
        </div>
        <div class="col-sm-1 text-right">
            <button title='Listar Requsição' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'requisicao:lista' %}">
            <span class="glyphicon glyphicon-list"></span></button>
        </div>
        <div class="col-sm-1 text-right">
             <button title='Novo Item de Requisição' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'requisicao:cria' %}">
            <span class="glyphicon glyphicon-plus"></span></button>
        </div>
    </form>
</div> 
{% endblock %}
{% block main %}
<hr>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
	<div class="row">
  		<div class="col-sm-4">
    		<p><strong>Requisição</strong></p>
    		<p>{{requisicao.id}}</p>
  		</div>
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
        <p><strong>Situação</strong></p>
        {% if requisicao.situacao %}
          <p><strong class='text-success'>Enviada</strong></p>
        {% else %}
          <p><strong class='text-danger'>Aberta</strong></p>
        {% endif %}
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
  		</div>
	</div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
<hr>
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Criado</strong></p>
        <p class='text-muted'>{{requisicao.criado}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Modificado</strong></p>
        <p class='text-muted'>{{requisicao.atualizado}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Por</strong></p>
        <p class='text-muted'>{{requisicao.usuario}}</p>
      </div>
  </div>
</div>
{% endblock %}

requisicao/templates/requisicao_lista.html
{% extends 'base.html' %}
{% block header %}
<div class="row">
    <div class="col-sm-4">
        <h4>Materiais: Requisições</h4>
    </div>
    <form method='GET' action=''>
	    <div class="col-sm-4">
	        <div class="input-group">
	            <input name="q" class="form-control" id="search" type="text" placeholder="Pesquisar Requisição" value='{{request.GET.q}}'>
		            <span class="input-group-btn">
	                <button title='Pesquisar' class="btn btn-primary" type="submit">
	                    <span class="glyphicon glyphicon-search"></span>
	                </button>
	            </span>
	        </div>
		</div> <!-- Pesquisa -->
    </form>
    <div class="col-sm-2">
    </div>
    <form>
    	<div class="col-sm-1 text-center">
        	<button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'requisicao:lista' %}">
	        	<span class="glyphicon glyphicon-refresh"></span></button>
    	</div>
    	<div class="col-sm-1 text-center">
        	<button title='Nova Requisicao' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'requisicao:cria' %}">
	        	<span class="glyphicon glyphicon-plus"></span></button>
    	</div>
   	</form>
</div>
{% endblock %}
{% block main %}
	<br><br>
	<div class='row'>	<!-- Cabeçalho-->
		<div class='col-sm-12'>
		    <ul class="list-inline">
		    	<div class='col-sm-1 text-center'>
		        	<li><strong>ID</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2'>
		        	<li><strong>REQUISIÇÃO</strong></li>       
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-4'>
		        {% if perms.fornecedor.pode_administrar %}
		       		<li><strong>USUÁRIO</strong></li>
			    {% else %}
			    	<li><strong>MODIFICADO</strong></li>
			    {% endif %}
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2 text-center'>
		        	<li><strong>OPÇÕES</strong></li>
		    	</div>
		    </ul>
	    </div>
    </div><hr>
	{% for obj in requisicoes %} <!-- Itens-->
	    <div class='row'><br> 
	    	<div class='col-sm-12 text-muted'>
			    <ul class="list-inline">
			    <div class='col-sm-1'>
			        <li class='text-center'>{{forloop.counter}}</li>
			    </div>
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2'>
			        <li>{{obj.id}}</li>
			    </div>       
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-4'>
			    {% if perms.requisicao.pode_administrar %}
			    	<li>{{obj.usuario}}</li>
			    {% else %}
			    	<li>{{obj.atualizado}}</li>
			    {% endif %}
			    </div>
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2 text-center'>
	                <a href='{% url "requisicao:detalhe" obj.id %}'>
	                   	<span title='Visualizar' class="glyphicon glyphicon glyphicon-zoom-in"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <a href='{% url "requisicao:enviar" obj.id %}'>
	                   	<span title='Enviar requisição' class="glyphicon glyphicon-ok"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <a href='{% url "requisicao:listadeitens" obj.id %}'>
	                   	<span title='Itens' class="glyphicon glyphicon-list-alt"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <!-- <a href='{% url "armazem:apaga" obj.id %}'> -->
	                <a href="javascript:func()" onclick="confirmacao('{% url "requisicao:apaga" obj.id %}')">
	                   	<span style="color:red" title='Excluir' class="glyphicon glyphicon-trash"></span>
	                </a>
			    </div>
			    </ul>
		    </div>
	  	</div>
	{% endfor %}
	<hr>
	<div class='text-center'>
	<div class="pagination"> <!-- Paginação-->
	    <span class="step-links">
	        {% if requisicoes.has_previous %}
	            <a href="?{{ page_request_var }}={{requisicoes.previous_page_number }}"><strong><< </strong></a>
	        {% endif %}

	        <span class="current">
	            {{ requisicoes.number }} / {{ requisicoes.paginator.num_pages }}
	        </span>

	        {% if requisicoes.has_next %}
	            <a href="?{{ page_request_var }}={{ requisicoes.next_page_number }}"><strong> >></strong></a>
	        {% endif %}
	    </span>
	</div>
	</div>
{% endblock %}
{% block jquery %}
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover esta Requisicao ?");
   			if (resposta == true) {
      			window.location.href = id;
   			}
		}
	</script>
{% endblock %}

requisicao/templates/requisicao_listadeitens.html
{% extends 'base.html' %}
{% block header %}
<div class="row">
    <div class="col-sm-4">
        <h4>Materiais: Requisição - Itens</h4>
    </div>
    <form method='GET' action=''>
	    <div class="col-sm-4">
	        <div class="input-group">
	            <input name="q" class="form-control" id="search" type="text" placeholder="Pesquisar Itens de requisição" value='{{request.GET.q}}'>
		            <span class="input-group-btn">
	                <button title='Pesquisar' class="btn btn-primary" type="submit">
	                    <span class="glyphicon glyphicon-search"></span>
	                </button>
	            </span>
	        </div>
		</div> <!-- Pesquisa -->
    </form>
    <div class="col-sm-4">
    </div>
    <form>
        <div class="col-sm-1 text-center">
        </div>
    	<div class="col-sm-1 text-center">
        	<button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="">
	        	<span class="glyphicon glyphicon-refresh"></span></button>
    	</div>
    	<div class="col-sm-1 text-center">
            <button title='Listar Requisições' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'requisicao:lista' %}">
            <span class="glyphicon glyphicon-list"></span></button>
        </div>
    	<div class="col-sm-1 text-center">
        		<button title='Novo Item de Requisição' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'requisicao:requisicaoitemcria' requisicao.id %}">
	        	<span class="glyphicon glyphicon-plus"></span></button>
    	</div>
   	</form>
</div>
{% endblock %}
{% block main %}
	<br><br>
	<div class='row'>	<!-- Cabeçalho-->
		<div class='col-sm-12'>
		    <ul class="list-inline">
		    	<div class='col-sm-1 text-center'>
		        	<li><strong>ID</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2'>
		        	<li><strong>ITEM</strong></li>       
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-4'>
		        	<li><strong>SITUAÇÃO</strong></li>
		        </div>
		        <div class='col-sm-1'>
		        </div>
		        <div class='col-sm-2 text-center'>
		        	<li><strong>OPÇÕES</strong></li>
		    	</div>
		    </ul>
	    </div>
    </div><hr>
	{% for obj in listadeitens %} <!-- Itens-->
	    <div class='row'><br> 
	    	<div class='col-sm-12 text-muted'>
			    <ul class="list-inline">
			    <div class='col-sm-1'>
			        <li class='text-center'>{{forloop.counter}}</li>
			    </div>
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2'>
			        <li>{{obj.item}}</li>
			    </div>       
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-4'>
				{% if obj.situacao %}
		          <p><strong class='text-success'>Atendido</strong></p>
		        {% else %}
		          <p><strong class='text-danger'>Pendente</strong></p>
		        {% endif %}   
			    </div>
			    <div class='col-sm-1'>
			    </div>
			    <div class='col-sm-2 text-center'>
	                <a href='{% url "requisicao:requisicaoitemdetalhe" obj.id %}'>
	                   	<span title='Visualizar' class="glyphicon glyphicon glyphicon-zoom-in"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <a href=''>
	                   	<span title='Atender' class="glyphicon glyphicon-ok"></span>
	                </a>&nbsp;&nbsp;&nbsp;	                
	                <a href='{% url "requisicao:requisicaoitemedita" obj.id %}'>
	                   	<span title='Editar' class="glyphicon glyphicon-pencil"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <a href="javascript:func()" onclick="confirmacao('{% url "requisicao:requisicaoitemapaga" obj.id %}')">
	                   	<span style="color:red" title='Excluir' class="glyphicon glyphicon-trash"></span>
	                </a>
			    </div>
			    </ul>
		    </div>
	  	</div>
	{% endfor %}
	<hr>
	<div class='text-center'>
	<div class="pagination"> <!-- Paginação-->
	    <span class="step-links">
	        {% if listadeitens.has_previous %}
	            <a href="?{{ page_request_var }}={{ listadeitens.previous_page_number }}"><strong><< </strong></a>
	        {% endif %}

	        <span class="current">
	            {{ listadeitens.number }} / {{ listadeitens.paginator.num_pages }}
	        </span>

	        {% if listadeitens.has_next %}
	            <a href="?{{ page_request_var }}={{ listadeitens.next_page_number }}"><strong> >></strong></a>
	        {% endif %}
	    </span>
	</div>
	</div>
{% endblock %}
{% block jquery %}
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover este item da Requisicao ?");
   			if (resposta == true) {
      			window.location.href = id;
   			}
		}
	</script>
{% endblock %}

requisicao/templates/requsitcaoitem_form.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block main %}
<form method='POST' action=''>{% csrf_token %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-3">
        <h4>Materiais: Item de Requsição</h4>
    </div>   
    <div class="col-sm-7">
    </div>   
    <div class="col-sm-1 text-center">
        <button title='Alterar item de Requisição' class='btn btn-primary btn-sm' type='submit'>
          <span class="glyphicon glyphicon-check"></span>
        </button>
    </div>
    <div class="col-sm-1 text-center">
        <button title='Listar Itens de requisicao' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'requisicao:listadeitens' requisicao.id %}">
          <span class="glyphicon glyphicon-list"></span>
        </button>
    </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  <hr>  <div class="row">
      <div class="col-sm-4">
        <p><strong>Item</strong></p>
        <p>{{formItem.item}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Quantidade</strong></p>
        <p>{{formItem.quantidade}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
       </div>
  </div>
</div>
</form>
{% endblock %}