core/urls.py
from django.conf.urls import url, include

from .views	import usuario_detalhe, home

urlpatterns = [
   url(r'^home/', home, name='home'),
   url(r'^usuario/', usuario_detalhe, name='usuario'),
]

fiocruz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.urls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^armazem/', include('armazem.urls', namespace='armazem')),
    url(r'^compra/', include('compra.urls', namespace='compra')),
    url(r'^fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    url(r'^item/', include('item.urls', namespace='item')),
    url(r'^requisicao/', include('requisicao.urls', namespace='requisicao')),
    url(r'^usuario/', include('core.urls', namespace='core')),
    url(r'^login/',views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/',views.logout_then_login, { 'login_url': '/login/'}, name='logout')
]

fornecedor/urls.py
from django.conf.urls import url, include

from .views	import fornecedor_lista, fornecedor_apaga, fornecedor_detalhe, fornecedor_edita, fornecedor_cria

urlpatterns = [
    url(r'^$', fornecedor_lista, name='lista'),
    url(r'^cria/$', fornecedor_cria, name='cria'),
    url(r'^apaga/(?P<id>\d+)/$', fornecedor_apaga, name='apaga'),
    url(r'^detalhe/(?P<id>\d+)/$', fornecedor_detalhe, name='detalhe'),
    url(r'^edita/(?P<id>\d+)/$', fornecedor_edita, name='edita')
]

fornecedor/models.py
from django.conf	import settings
from django.core.urlresolvers import reverse
from django.db import models

from core.models import Estado
from core.models import Municipio

class Fornecedor(models.Model):

	razaosocial	= models.CharField(max_length=80,null=False)
	nomefantasia= models.CharField(max_length=40,null=False)
	cnpj		= models.CharField(max_length=14,null=False)
	atividade	= models.CharField(max_length=20,null=False)
	estado		= models.ForeignKey(Estado,on_delete=models.PROTECT)
	cidade		= models.ForeignKey(Municipio,on_delete=models.PROTECT)	
	bairro		= models.CharField(max_length=40,null=False)	
	endereco 	= models.CharField(max_length=40,null=False)
	numero		= models.CharField(max_length=6,null=False)
	complemento	= models.CharField(max_length=40,null=True)
	cep			= models.CharField(max_length=8,null=False)
	telefone	= models.CharField(max_length=20,null=False)
	contato		= models.CharField(max_length=40,null=False)
	email		= models.EmailField(null=True)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)
	situacao	= models.BooleanField()
	usuario	    = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)

	class Meta:
		ordering = ['-atualizado','-criado']
		permissions = (
            ('pode_administrar', 'Pode Administrar'),
        )
		
	def __unicode__(self):
		return self.nomefantasia

	def __str__(self):
		return self.nomefantasia

	def get_absolute_url(self):
		return reverse('fornecedor:detalhe', kwargs={'id':self.id})

fornecedor/forms.py
from django import forms

from .models import Fornecedor
from core.models import Estado, Municipio

class FornecedorForm(forms.ModelForm):


#	telefone	= forms.RegexField(regex=r'^\+?1?\d{9,15}$',error_message = ("Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed."))
	complemento = forms.CharField(required=False)
	email		= forms.EmailField(required=False)
	situacao 	= forms.BooleanField(required=False, label="situacao")
#	cidade 		= forms.ModelChoiceField(queryset=Municipio.objects.all().filter(estado_id=11))

	class Meta:
		model = Fornecedor
		fields = {
			'razaosocial',
			'nomefantasia',
			'atividade',
			'cnpj',
			'estado',
			'cidade',
			'bairro',
			'endereco',
			'numero',
			'complemento',
			'cep',
			'telefone',
			'contato',
			'email',
			'situacao',
		}

fornecedor/views.py
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from .forms import FornecedorForm
from .models import Fornecedor

@login_required
def fornecedor_apaga(request,id=None):
	instance = get_object_or_404(Fornecedor,id=id)
	try:
		instance.delete()
		messages.success(request,' Fornecedor foi excluido.')
	except IntegrityError:
		messages.warning(request,' O Fornecedor "%s" não pode ser excluído, devido a vínculo com outra informação.' % instance.nomefantasia)
	return redirect('fornecedor:lista')

@login_required
def fornecedor_cria(request):
	form = FornecedorForm(request.POST or None)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.usuario = request.user
		instance.save()
		messages.success(request,' Fornecedor foi criado.')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = {'form':form }
	return render(request,'fornecedor_form.html', context)

@login_required
def fornecedor_detalhe(request,id):
	queryset_detalhe = Fornecedor.objects.get(id=id)
	context = { 'fornecedor':queryset_detalhe}
	return render(request,'fornecedor_detalhe.html', context)

@login_required
def fornecedor_edita(request,id=None):
	instance = get_object_or_404(Fornecedor,id=id)
	form = FornecedorForm(request.POST or None, instance=instance)
	if form.is_valid():
		instance = form.save(commit=False)
		instance.usuario = request.user
		instance.save()
		messages.success(request,' Fornecedor foi modificado.')
		return HttpResponseRedirect(instance.get_absolute_url())
	context = { 'instance':instance, 'form':form }
	return render(request,'fornecedor_form.html', context)

@login_required
def fornecedor_lista(request):
	queryset_list = Fornecedor.objects.all() 
	# queryset = Armazem.objects.all().order_by('-criado,-atualizado') 
	page_request_var='Pagina'
	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(
			Q(nomefantasia__icontains=query)|
			Q(razaosocial__icontains=query)
			)
	paginator = Paginator(queryset_list, 8)
	page = request.GET.get(page_request_var)
	try:
		queryset_list = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset_list = paginator.page(paginator.num_pages)
	context = { 'fornecedores':queryset_list,
				'page_request_var':page_request_var }
	return render(request,'fornecedor_lista.html', context)

fornecedor/templates/fornecedor_detalhe.html
{% extends 'base.html' %}

{% block header %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-4">
        <h4>Materiais: Fornecedor - Detalhe</h4>
    </div>   
    <div class="col-sm-5">
    </div>   
    <form>
        <div class="col-sm-1 text-right">
            <button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="{{ fornecedor.get_absolute_url }}">
            <span class="glyphicon glyphicon-refresh"></span></button>
        </div>
        <div class="col-sm-1 text-right">
            <button title='Listar Fornecedores' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'fornecedor:lista' %}">
            <span class="glyphicon glyphicon-list"></span></button>
        </div>
        <div class="col-sm-1 text-right">
        {% if perms.fornecedor.pode_administrar %}
            <button title='Novo Fornecedor' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'fornecedor:cria' %}">
            <span class="glyphicon glyphicon-plus"></span></button>
        {% endif %}
        </div>
    </form>
</div> 
{% endblock %}
{% block main %}
<hr>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
	<div class="row">
  		<div class="col-sm-4">
    		<p><strong>Razão Social</strong></p>
    		<p>{{fornecedor.razaosocial}}</p>
  		</div>
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
    		<p><strong>Nome Fantasia</strong></p>
    		<p>{{fornecedor.nomefantasia}}</p>
  		</div>
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
    		<p><strong>CNPJ</strong></p>
    		<p>{{fornecedor.cnpj}}</p>
  		</div>
	</div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Atividade</strong></p>
        <p>{{fornecedor.atividade}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Bairro</strong></p>
        <p>{{fornecedor.bairro}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Estado</strong></p>
        <p>{{fornecedor.estado}}</p>
      </div>

  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
	<div class="row">
      <div class="col-sm-4">
        <p><strong>Cidade</strong></p>
        <p>{{fornecedor.cidade}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Complemento</strong></p>
        <p>{% if fornecedor.complemento %} {{fornecedor.complemento}} {% endif %}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
          <p><strong>CEP</strong></p>
          <p>{{fornecedor.cep}}</p>
      </div>
  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
  <div class="row">      
      <div class="col-sm-4">
        <p><strong>Endereço</strong></p>
        <p>{{fornecedor.endereco}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Número</strong></p>
        <p>{{fornecedor.numero}}</p>
      </div>
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
          <p><strong>Situação</strong></p>
          {% if fornecedor.situacao %}
            <p><strong class='text-success'>APTO</strong></p>
          {% else %}
            <p><strong class='text-danger'>NÃO APTO</strong></p>
          {% endif %}
  		</div>
	</div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 3-->
    <div class="row">
        <div class="col-sm-4">
          <p><strong>Contato</strong></p>
          <p>{{fornecedor.contato}}</p>
        </div>
        <div class="col-sm-1">
        </div>
        <div class="col-sm-3">
          <p><strong>E-mail</strong></p>
          <p>{% if fornecedor.email %} {{fornecedor.email}} {% endif %}</p>
        </div>
        <div class="col-sm-1">
        </div>
        <div class="col-sm-3">
          <p><strong>Telefone</strong></p>
          <p>{{fornecedor.telefone}}</p>
        </div>
      </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 4-->
<hr>
    <div class="row">
        <div class="col-sm-4">
          <p><strong>Criado</strong></p>
          <p class='text-muted'>{{fornecedor.criado}}</p>
        </div>
        <div class="col-sm-1">
        </div>
        <div class="col-sm-3">
          <p><strong>Modificado</strong></p>
          <p class='text-muted'>{{fornecedor.atualizado}}</p>
        </div>
        <div class="col-sm-1">
        </div>
        <div class="col-sm-3">
          <p><strong>Por</strong></p>
          <p class='text-muted'>{{fornecedor.usuario}}</p>
        </div>
    </div>
</div>
{% endblock %}

fornecedor/templates/fornecedor_form.html
 {% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block main %}
<form method='POST' action=''>{% csrf_token %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-3">
        <h4>Materiais: Fornecedores</h4>
    </div>   
    <div class="col-sm-7">
    </div>   
    <div class="col-sm-1 text-center">
        <button title='Adicionar Fornecedor' class='btn btn-primary btn-sm' type='submit'>
          <span class="glyphicon glyphicon-check"></span>
        </button>
    </div>
    <div class="col-sm-1 text-center">
        <button title='Listar Fornecedor' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'fornecedor:lista' %}">
          <span class="glyphicon glyphicon-list"></span>
        </button>
    </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  <hr>
	<div class="row">
  		<div class="col-sm-4">
    		<p><strong>Razão Social</strong></p>
    		<p>{{form.razaosocial}}</p>
  		</div>
        <div class="col-sm-1">
        </div>
  		<div class="col-sm-3">
    		<p><strong>Nome Fantasia</strong></p>
    		<p>{{form.nomefantasia}}</p>
  		</div>
        <div class="col-sm-1">
        </div>
  		<div class="col-sm-3">
    		<p><strong>CNPJ</strong></p>
    		<p>{{form.cnpj}}</p>
  		</div>
	</div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 2-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Atividade</strong></p>
        <p>{{form.atividade}}</p>
      </div>
        <div class="col-sm-1">
        </div>
      <div class="col-sm-3">
        <p><strong>Bairro</strong></p>
        <p>{{form.bairro}}</p>
      </div>
        <div class="col-sm-1">
        </div>
      <div class="col-sm-3">
        <p><strong>Estado</strong></p>
        <p>{{form.estado}}</p>
      </div>
  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 3-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Cidade</strong></p>
        <p>{{form.cidade}}</p>    
      </div>
        <div class="col-sm-1">
        </div>
     <div class="col-sm-3">
        <p><strong>Complemento</strong></p>
        <p>{{form.complemento}}</p>
      </div>
        <div class="col-sm-1">
        </div>
      <div class="col-sm-3">
        <p><strong>CEP</strong></p>
        <p>{{form.cep}}</p>
      </div>
  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 3-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Endereco</strong></p>
        <p>{{form.endereco}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Número</strong></p>
        <p>{{form.numero}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><label for="situacao"><strong>Apto</strong></label></p>
        {% if instance.situacao %}
            <p><input type="checkbox" name="situacao" id="situacao" CHECKED ></p>
        {% else %}
            <p><input type="checkbox" name="situacao" id="situacao" ></p>
        {% endif %}
        </p>
      </div>
  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 4-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Contato</strong></p>
        <p>{{form.contato}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>E-mail</strong></p>
        <p>{{form.email}}</p>      
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Telefone</strong></p>
        <p>{{form.telefone}}</p>
      </div>
  </div>
</div>
</form>
<p id='texto'></p>
{% endblock %}

{% block jquery %}
      <script>
        $('select[name="estado"]').click(function() {
            var id_do_estado = $('#id_estado').val()     
            $.ajax({
              url = 'http://localhost:8000/fornecedor/cria/',
              dataType: 'json',
              success: function(retorno) {
                $.each(retorno.id_cidade, function() {
                  var cidade = this;
                  alert(cidade.nome);
                })
              }
            })


            $('#texto').text(id_do_estado);
        });
      </script>
{% endblock %}

fornecedor/templates/fornecedor_lista.html
{% extends 'base.html' %}
{% block header %}
<div class="row">
    <div class="col-sm-4">
        <h4>Materiais: Fornecedores</h4>
    </div>
    <form method='GET' action=''>
	    <div class="col-sm-4">
	        <div class="input-group">
	            <input name="q" class="form-control" id="search" type="text" placeholder="Pesquisar Fornecedor" value='{{request.GET.q}}'>
		            <span class="input-group-btn">
	                <button title='Pesquisar' class="btn btn-primary" type="submit">
	                    <span class="glyphicon glyphicon-search"></span>
	                </button>
	            </span>
	        </div>
		</div> <!-- Pesquisa -->
    </form>
    <div class="col-sm-2">
    </div>
    <form>
    	<div class="col-sm-1 text-center">
        	<button title='Atualizar fornecedor' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'fornecedor:lista' %}">
	        	<span class="glyphicon glyphicon-refresh"></span></button>
    	</div>
    	<div class="col-sm-1 text-center">
    	{% if perms.fornecedor.pode_administrar %}
        	<button title='Novo fornecedor' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'fornecedor:cria' %}">
	        	<span class="glyphicon glyphicon-plus"></span></button>
	    {% endif %}
	    </div>
   	</form>
</div>
{% endblock %}
{% block main %}
	<br><br>
	<div class='row'>	<!-- Cabeçalho-->
		<div class='col-sm-12'>
		    <ul class="list-inline">
		    	<div class='col-sm-1 text-center'>
		        	<li><strong>ID</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-4'>
		        	<li><strong>NOME FANTASIA</strong></li>       
		        </div>
		        <div class='col-sm-1'>
		        </div>
		        <div class='col-sm-2'>
		        	<li><strong>SITUAÇÃO</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2 text-center'>
		        	<li><strong>OPÇÕES</strong></li>
		    	</div>
		    </ul>
	    </div>
    </div><hr>
	{% for obj in fornecedores %} <!-- Itens-->
	    <div class='row'><br> 
	    	<div class='col-sm-12 text-muted'>
			    <ul class="list-inline">
			    <div class='col-sm-1'>
			        <li class='text-center'>{{forloop.counter}}</li>
			    </div>
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-4'>
			        <li>{{obj.nomefantasia}}</li>
			    </div>       
			    <div class='col-sm-1'>
			    </div>
			    <div class='col-sm-2'>
			    	<li><strong>
			    	{% if obj.situacao %}
		        		APTO
			    	{% else %}
			    		NÃO APTO
			    	{% endif %}
			    	</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2 text-center'>
	                <a href='{{ obj.get_absolute_url }}'>
	                   	<span title='Visualizar' class="glyphicon glyphicon-zoom-in"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                {% if perms.fornecedor.pode_administrar %}
	                <a href='{% url "fornecedor:edita" obj.id %}'>
	                   	<span title='Editar' class="glyphicon glyphicon-pencil"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                <!-- <a href='{% url "fornecedor:apaga" obj.id %}'> -->
	                <a href="javascript:func()" onclick="confirmacao('{% url "fornecedor:apaga" obj.id %}')">
	                   	<span style="color:red" title='Excluir' class="glyphicon glyphicon-trash"></span>
	                </a>
	                {% endif %}
			    </div>
			    </ul>
		    </div>
	  	</div>
	{% endfor %}
	<hr>
	<div class='text-center'>
	<div class="pagination"> <!-- Paginação-->
	    <span class="step-links">
	        {% if fornecedores.has_previous %}
	            <a href="?{{ page_request_var }}={{ fornecedores.previous_page_number }}"><strong><< </strong></a>
	        {% endif %}

	        <span class="current">
	            {{ fornecedores.number }} / {{ fornecedores.paginator.num_pages }}
	        </span>

	        {% if fornecedores.has_next %}
	            <a href="?{{ page_request_var }}={{ fornecedores.next_page_number }}"><strong> >></strong></a>
	        {% endif %}
	    </span>
	</div>
	</div>
{% endblock %}
{% block jquery %}
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover este fornecedor ?");
   			if (resposta == true) {
      			window.location.href = id;
   			}
		}
	</script>
{% endblock %}