compra/urls.py
from django.conf.urls import url, include

from .views	import compra_cria, compra_lista, compra_detalhe, compra_edita, compra_apaga
from .views import listadeitens,compraitem_detalhe, compraitem_cria, compraitem_apaga, compraitem_edita

urlpatterns = [
    url(r'^$', compra_lista, name='lista'),
    url(r'^cria/$', compra_cria, name='cria'),
    url(r'^apaga/(?P<id>\d+)/$', compra_apaga, name='apaga'),
    url(r'^detalhe/(?P<id>\d+)/$', compra_detalhe, name='detalhe'),
    url(r'^edita/(?P<id>\d+)/$', compra_edita, name='edita'),
    url(r'^listadeitens/(?P<id>\d+)/$', listadeitens, name='listadeitens'),
    url(r'^compraitemapaga/(?P<id>\d+)/$', compraitem_apaga, name='compraitemapaga'),
    url(r'^compraitemdetalhe/(?P<id>\d+)/$', compraitem_detalhe, name='compraitemdetalhe'),
    url(r'^compraitemcria/(?P<id>\d+)/$', compraitem_cria, name='compraitemcria'),
    url(r'^compraitemedita/(?P<id>\d+)/$', compraitem_edita, name='compraitemedita'),
]

core/urls.py
from django.conf.urls import url, include

from .views	import usuario_detalhe, home

urlpatterns = [
   url(r'^home/', home, name='home'),
   url(r'^usuario/', usuario_detalhe, name='usuario'),
]

fiocruz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.urls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^armazem/', include('armazem.urls', namespace='armazem')),
    url(r'^compra/', include('compra.urls', namespace='compra')),
    url(r'^fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    url(r'^item/', include('item.urls', namespace='item')),
    url(r'^requisicao/', include('requisicao.urls', namespace='requisicao')),
    url(r'^usuario/', include('core.urls', namespace='core')),
    url(r'^login/',views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/',views.logout_then_login, { 'login_url': '/login/'}, name='logout')
]

compra/models.py
from django.db import models
from django.db.models import Sum
# Create your models here.
from django.conf	import settings
from django.core.urlresolvers import reverse
from datetime import datetime, timedelta

from item.models import Item
from fornecedor.models import Fornecedor
from armazem.models import Armazem

class Compra(models.Model):
# Falta incluir Fornecedor
	notafiscal	= models.CharField(max_length=20,null=False)
	fornecedor  = models.ForeignKey(Fornecedor,on_delete=models.PROTECT)
	data_compra	= models.DateField(default=datetime.today)
	data_entrega= models.DateField(default=datetime.today)
	data_pagamento= models.DateField(default=datetime.today()+timedelta(days=90))
	situacao	= models.BooleanField(default=False)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)
	usuario	    = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)

	class Meta:
		ordering = ['-atualizado','-criado']
		permissions = (
            ('pode_administrar', 'Pode Administrar'),
        )

	def __str__(self):
		return self.id		

	def __unicode__(self):
		return self.id	

	def get_absolute_url(self):
		return reverse('compra:detalhe', kwargs={'id':self.id})

class ItemCompra(models.Model):

	item 		= models.ForeignKey(Item,on_delete=models.PROTECT)	
	quantidade 	= models.IntegerField(default=1)
	custo 		= models.DecimalField(max_digits=10,decimal_places=2)
	compra      = models.ForeignKey(Compra,on_delete=models.CASCADE)
	armazem		= models.ForeignKey(Armazem,on_delete=models.PROTECT)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)
	requisitante= models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT)

	class Meta:
		ordering = ['item']
		permissions = (
            ('pode_administrar', 'Pode Administrar'),
        )

	def __str__(self):
		return self.id

	def get_absolute_url(self):
		return reverse('compra:compraitemdetalhe', kwargs={'id':self.id})

compra/forms.py
from django import forms

from .models import Compra, ItemCompra
from fornecedor.models import Fornecedor
from item.models import Item

class CompraForm(forms.ModelForm):

    class Meta:
    	model = Compra
    	fields = {
    		'notafiscal',
    		'fornecedor',
			'data_compra',
			'data_entrega',
			'data_pagamento',
			'situacao',
		}

class ItemCompraForm(forms.ModelForm):

	item = forms.ModelChoiceField(queryset=Item.objects.all())

	class Meta:
		model = ItemCompra
		fields = {
			'item',
			'quantidade',
			'custo',
			'armazem',
			'requisitante',
		}	

compra/views.py
from django.contrib import messages
from django.contrib.auth.decorators import permission_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.db.models import Sum
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError

from .forms import CompraForm,ItemCompraForm
from .models import Compra,ItemCompra
from fornecedor.models import Fornecedor


@login_required
def compra_apaga(request,id=None):
	instance = get_object_or_404(Compra,id=id)
	if instance.situacao: 
		messages.warning(request,' Compra fechada, não é possivel excluir.')
		return redirect('compra:lista')
	else:
		try:
			instance.delete()
			messages.success(request,' Compra foi excluida.')
		except IntegrityError:
			messages.warning(request,' O Compra "%s" não pode ser excluído, devido a vínculo com outra informação.' % instance.nome)
		return redirect('compra:lista')

@login_required
def compra_cria(request): 
	form = CompraForm(request.POST or None)	
	if form.is_valid():
			instance = form.save(commit=False)
			if instance.situacao:
				messages.warning(request,' Ao fechar a compra é necessário, existir pelo menos um item vinculado.')
			else:
				if instance.data_entrega < instance.data_compra or instance.data_pagamento < instance.data_entrega:  # Criar FUNCAo 1
					messages.warning(request,' Verifique as datas de entrega e pagamento.')
				else:
					if instance.fornecedor.situacao:
						instance.usuario = request.user
						instance.save()
						messages.success(request,' Compra foi criada.')
						return HttpResponseRedirect(instance.get_absolute_url())
					else:
						messages.warning(request,' Fornecedor não esta apto, somente fornecedores aptos são permitidos a compra.')				
	context = { 'form':form }
	return render(request,'compra_form.html', context)

@login_required
def compra_detalhe(request,id):
	queryset_detalhe = Compra.objects.get(id=id)
	queryset_detalhe_item = ItemCompra.objects.filter(compra__id=id)
	queryset_detalhe_item_soma = ItemCompra.objects.filter(compra__id=id).aggregate(Sum('custo'))
	queryset_detalhe_quantidade_soma = ItemCompra.objects.filter(compra__id=id).count()
	context = { 'compra':queryset_detalhe,
				'itemcompra':queryset_detalhe_item,
				'itemcomprasoma':queryset_detalhe_item_soma,
				'itemcompraquantidadesoma':queryset_detalhe_quantidade_soma,
				} 
	return render(request,'compra_detalhe.html', context)

@login_required
def compra_edita(request,id=None):	
	instance = get_object_or_404(Compra,id=id)
	form = CompraForm(request.POST or None, instance=instance)
	if instance.situacao: 
		messages.warning(request,' Compra fechada, não é possivel editar.')
		return redirect('compra:lista')
	else:
		if form.is_valid():
			if ItemCompra.objects.filter(compra__id=id).count() == 0:
				messages.warning(request,' Ao fechar a compra é necessário, existir pelo menos um item vinculado.')
			else:
				instance = form.save(commit=False)
				if instance.data_entrega < instance.data_compra or instance.data_pagamento < instance.data_entrega:   # CRIAR FUNCAO 1
					messages.warning(request,' Verifique as datas de entrega e pagamento.')
				else:
					instance.usuario = request.user
					instance.save()
					messages.success(request,' Compra foi modificado.')
					return HttpResponseRedirect(instance.get_absolute_url())
	context = { 'instance':instance, 'form':form,}
	return render(request,'compra_form.html', context)

@login_required
def compra_lista(request):
	queryset_list = Compra.objects.all() 
	# queryset = Armazem.objects.all().order_by('-criado,-atualizado') 
	page_request_var='Pagina'
	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(
			Q(notafiscal__icontains=query)|
			Q(data_compra__icontains=query)
			)
	paginator = Paginator(queryset_list, 8)
	page = request.GET.get(page_request_var)
	try:
		queryset_list = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset_list = paginator.page(paginator.num_pages)
	context = { 'compras':queryset_list,
				'page_request_var':page_request_var 
				}
	return render(request,'compra_lista.html', context) 

@login_required
def compraitem_apaga(request,id=None):
	instance = get_object_or_404(ItemCompra,id=id)
	if instance.compra.situacao: 
		messages.warning(request,' Compra fechada, não é possivel excluir.')
		return redirect('compra:lista')
	else:
		try:
			instance.delete()
			messages.success(request,' Item da Compra foi excluida.')
		except IntegrityError:
			messages.warning(request,' O Item da Compra "%s" não pode ser excluído, devido a vínculo com outra informação.' % instance.nome)
		return redirect('compra:listadeitens',instance.compra.id)

@login_required
def compraitem_cria(request,id):
	formItem = ItemCompraForm(request.POST or None)
	queryset_compra = Compra.objects.get(id=id)
	if queryset_compra.situacao: 
		messages.warning(request,' Compra fechada, não é possivel criar itens.')
		return redirect('compra:listadeitens',id)
	else:
		if formItem.is_valid():
			instance = formItem.save(commit=False)
			instance.compra = queryset_compra
			instance.usuario = request.user
			instance.save()
			messages.success(request,' Item de Compra foi criado.')
			return HttpResponseRedirect(instance.get_absolute_url())
		context = { 'formItem': formItem,
					'compra':queryset_compra, }
		return render(request,'compraitem_form.html', context)

@login_required
def compraitem_edita(request,id=None):	
	instance = get_object_or_404(ItemCompra,id=id)
	queryset_compra = Compra.objects.get(id=instance.compra.id)
	form = ItemCompraForm(request.POST or None, instance=instance)
	if queryset_compra.situacao: 
		messages.warning(request,' Compra fechada, não é possivel editar itens.')
		return redirect('compra:listadeitens',instance.compra.id)
	else:
		if form.is_valid():
				instance = form.save(commit=False)
				instance.usuario = request.user
				instance.save()
				messages.success(request,' item da Compra foi modificado.')
				return HttpResponseRedirect(instance.get_absolute_url())
	context = { 'formItem':form,
				'compra':queryset_compra,}
	return render(request,'compraitem_form.html', context)

@login_required
def compraitem_detalhe(request,id):
	queryset_detalhe = ItemCompra.objects.get(id=id)
	queryset_compra = Compra.objects.get(id=queryset_detalhe.compra.id)
	context = { 'compraitem':queryset_detalhe,
				'compra':queryset_compra, }
	return render(request,'compraitem_detalhe.html', context)

@login_required
def listadeitens(request,id):
	queryset_list = ItemCompra.objects.filter(compra=id)
	queryset_compra = Compra.objects.get(id=id)	
	# queryset = Armazem.objects.all().order_by('-criado,-atualizado') 
	page_request_var='Pagina'
	query = request.GET.get('q')
	if query:
		queryset_list = queryset_list.filter(item__nome__icontains=query)
	paginator = Paginator(queryset_list, 8)
	page = request.GET.get(page_request_var)
	try:
		queryset_list = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		queryset_list = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		queryset_list = paginator.page(paginator.num_pages)
	context = { 'listadeitens':queryset_list,
				'compra': queryset_compra,
				'page_request_var':page_request_var 
				}
	return render(request,'lista_de_itens.html', context)

compra/templates/compraItem_detalhe.html
{% extends 'base.html' %}

{% block header %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-4">
        <h4>Materiais: Item da Compra - Detalhe</h4>
    </div>   
    <div class="col-sm-5">
    </div>   
    <form>
        <div class="col-sm-1 text-right">
            <button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="{{ compraitem.get_absolute_url }}">
            <span class="glyphicon glyphicon-refresh"></span></button>
        </div>
        <div class="col-sm-1 text-right">
            <button title='Listar Itens de Compras' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'compra:listadeitens' compra.id %}">
            <span class="glyphicon glyphicon-list"></span></button>
        </div>
        <div class="col-sm-1 text-right">
        {% if perms.compra.pode_administrar %}
            <button title='Novo Item de Compra' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'compra:compraitemcria' compra.id %}">
            <span class="glyphicon glyphicon-plus"></span></button>
        {% endif %}
        </div>
    </form>
</div> 
{% endblock %}
{% block main %}

<hr>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Item</strong></p>
        <p>{{ compraitem.item }}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Quantidade</strong></p>
        <p>{{ compraitem.quantidade }}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Custo</strong></p>
        <p>{{ compraitem.custo }}
      </div>      
  </div>
</div>
<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Armazém</strong></p>
        <p>{{ compraitem.armazem}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
      </div>      
  </div>
</div>

<div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
<hr>
  <div class="row">
      <div class="col-sm-4">
        <p><strong>Criado</strong></p>
        <p class='text-muted'>{{ compraitem.criado }}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Modificado</strong></p>
        <p class='text-muted'>{{ compraitem.atualizado }}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Requisitante</strong></p>
        <p class='text-muted'>{{ compraitem.requisitante }}</p>
      </div>
  </div>
</div>
{% endblock %}

compra/templates/compra_form.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block main %}
<form method='POST' action=''>{% csrf_token %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-3">
        <h4>Materiais: Compras</h4>
    </div>   
    <div class="col-sm-7">
    </div>   
    <div class="col-sm-1 text-center">
        <button title='Adicionar Compra' class='btn btn-primary btn-sm' type='submit'>
          <span class="glyphicon glyphicon-check"></span>
        </button>
    </div>
    <div class="col-sm-1 text-center">
        <button title='Listar Compra' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'compra:lista' %}">
          <span class="glyphicon glyphicon-list"></span>
        </button>
    </div>
</div>

<div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  <hr>
	<div class="row">
  		<div class="col-sm-4">
        <p><strong>Fornecedor</strong></p>
        <p>{{form.fornecedor}}</p>
  		</div>
      <div class="col-sm-1">
      </div>
  		<div class="col-sm-3">
        <p><strong>Nota Fiscal</strong></p>
        <p>{{form.notafiscal}}</p>
  		</div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Fechar compra</strong></p>
        <p>{{form.situacao}}</p>
      </div>
  </div>
</div>
<div class="row col-sm-12">
<div class="row">
      <div class="col-sm-4">
        <p><strong>Data da Compra</strong></p>
        <p>{{form.data_compra}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Data da Entrega</strong></p>
        <p>{{form.data_entrega}}</p>
      </div>
      <div class="col-sm-1">
      </div>
      <div class="col-sm-3">
        <p><strong>Data do Pagamento</strong></p>
        <p>{{form.data_pagamento}}</p>
      </div>
      <div class="col-sm-3">
      </div>
</div>
</div>
</form>
{% endblock %}

compra/templates/compra_lista.html
{% extends 'base.html' %}
{% block header %}
<div class="row">
    <div class="col-sm-4">
        <h4>Materiais: Compras</h4>
    </div>
    <form method='GET' action=''>
	    <div class="col-sm-4">
	        <div class="input-group">
	            <input name="q" class="form-control" id="search" type="text" placeholder="Pesquisar Compra" value='{{request.GET.q}}'>
		            <span class="input-group-btn">
	                <button title='Pesquisar' class="btn btn-primary" type="submit">
	                    <span class="glyphicon glyphicon-search"></span>
	                </button>
	            </span>
	        </div>
		</div> <!-- Pesquisa -->
    </form>
    <div class="col-sm-2">
    </div>
    <form>
    	<div class="col-sm-1 text-center">
        	<button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'compra:lista' %}">
	        	<span class="glyphicon glyphicon-refresh"></span></button>
    	</div>
    	<div class="col-sm-1 text-center">
    	{% if perms.compra.pode_administrar %}
        	<button title='Nova Compra' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'compra:cria' %}">
	        	<span class="glyphicon glyphicon-plus"></span></button>
	    {% endif %}
    	</div>
   	</form>
</div>
{% endblock %}
{% block main %}
	<br><br>
	<div class='row'>	<!-- Cabeçalho-->
		<div class='col-sm-12'>
		    <ul class="list-inline">
		    	<div class='col-sm-1 text-center'>
		        	<li><strong>ID</strong></li>
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2'>
		        	<li><strong>NOTA FISCAL</strong></li>       
		        </div>
		        <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-4'>
		        	<li><strong>SITUAÇÃO</strong></li>
		        </div>
			    <div class='col-sm-1'>
	        	</div>
		        <div class='col-sm-2 text-center'>
		        	<li><strong>OPÇÕES</strong></li>
		    	</div>
		    </ul>
	    </div>
    </div><hr>
	{% for obj in compras %} <!-- Itens-->
	    <div class='row'><br> 
	    	<div class='col-sm-12 text-muted'>
			    <ul class="list-inline">
			    <div class='col-sm-1'>
			        <li class='text-center'>{{forloop.counter}}</li>
			    </div>
			    <div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2'>
			        <li>{{obj.notafiscal}}</li>
			    </div>       
			    <div class='col-sm-1'>
			    </div>
			    <div class='col-sm-4'>
			    {% if obj.situacao %}
			        <li>FECHADA</li>
			    {% else %}
			    	<li>ABERTA</li>
			    {% endif %}
			    </div>
			   	<div class='col-sm-1'>
	        	</div>
			    <div class='col-sm-2 text-center'>
	                <a href='{{ obj.get_absolute_url }}'>
	                   	<span title='Visualizar' class="glyphicon glyphicon glyphicon-zoom-in"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                {% if perms.compra.pode_administrar %}
			                <a href='{% url "compra:listadeitens" obj.id %}'>
			                   	<span title='Itens' class="glyphicon glyphicon-list-alt"></span>
			                </a>&nbsp;&nbsp;&nbsp;
			                <a href='{% url "compra:edita" obj.id %}'>
			                   	<span title='Editar' class="glyphicon glyphicon-pencil"></span>
			                </a>&nbsp;&nbsp;&nbsp;
			                <a href="javascript:func()" onclick="confirmacao('{% url "compra:apaga" obj.id %}')">
			                   	<span style="color:red" title='Excluir' class="glyphicon glyphicon-trash"></span>
			                </a>
	                {% endif %}
			    </div>
			    </ul>
		    </div>
	  	</div>
	{% endfor %}
	<hr>
	<div class='text-center'>
	<div class="pagination"> <!-- Paginação-->
	    <span class="step-links">
	        {% if compras.has_previous %}
	            <a href="?{{ page_request_var }}={{ compras.previous_page_number }}"><strong><< </strong></a>
	        {% endif %}

	        <span class="current">
	            {{ compras.number }} / {{ compras.paginator.num_pages }}
	        </span>

	        {% if compras.has_next %}
	            <a href="?{{ page_request_var }}={{ compras.next_page_number }}"><strong> >></strong></a>
	        {% endif %}
	    </span>
	</div>
	</div>
{% endblock %}
{% block jquery %}
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover esta compra ?");
   			if (resposta == true) {
      			window.location.href = id;
   			}
		}
	</script>
{% endblock %}

compra/templates/lista_de_itens.html
{% extends 'base.html' %}
{% block header %}
<div class="row">
    <div class="col-sm-4">
        <h4>Materiais: Compra - Itens</h4>
    </div>
    <form method='GET' action=''>
	    <div class="col-sm-4">
	        <div class="input-group">
	            <input name="q" class="form-control" id="search" type="text" placeholder="Pesquisar Itens da Compra" value='{{request.GET.q}}'>
		            <span class="input-group-btn">
	                <button title='Pesquisar' class="btn btn-primary" type="submit">
	                    <span class="glyphicon glyphicon-search"></span>
	                </button>
	            </span>
	        </div>
		</div> <!-- Pesquisa -->
    </form>
    <div class="col-sm-4">
    </div>
    <form>
        <div class="col-sm-1 text-center">
        </div>
    	<div class="col-sm-1 text-center">
        	<button title='Atualizar lista' class='btn btn-primary btn-sm' type='submit' formaction="">
	        	<span class="glyphicon glyphicon-refresh"></span></button>
    	</div>
    	<div class="col-sm-1 text-center">
            <button title='Listar Compras' class='btn btn-primary btn-sm' type='submit' formaction="{%  url 'compra:lista' %}">
            <span class="glyphicon glyphicon-list"></span></button>
        </div>
    	<div class="col-sm-1 text-center">
    	{% if perms.compra.pode_administrar %}
        		<button title='Novo Item de Compra' class='btn btn-primary btn-sm' type='submit' formaction="{% url 'compra:compraitemcria' compra.id %}">
	        	<span class="glyphicon glyphicon-plus"></span></button>
	    {% endif %}
    	</div>
   	</form>
</div>
{% endblock %}
{% block main %}
	<br><br>
	<div class='row'>	<!-- Cabeçalho-->
		<div class='col-sm-12'>
		    <ul class="list-inline">
		    	<div class='col-sm-1 text-center'>
		        	<li><strong>ID</strong></li>
		        </div>
		        <div class='col-sm-3'>
		        	<li><strong>ITEM</strong></li>       
		        </div>
		        <div class='col-sm-3'>
		        	<li><strong>QUANTIDADE</strong></li>
		        </div>
		        <div class='col-sm-3'>
		        	<li><strong>CUSTO</strong></li>
		        </div>
		        <div class='col-sm-2 text-center'>
		        	<li><strong>OPÇÕES</strong></li>
		    	</div>
		    </ul>
	    </div>
    </div><hr>
	{% for obj in listadeitens %} <!-- Itens-->
	    <div class='row'><br> 
	    	<div class='col-sm-12 text-muted'>
			    <ul class="list-inline">
			    <div class='col-sm-1'>
			        <li class='text-center'>{{forloop.counter}}</li>
			    </div>
			    <div class='col-sm-3'>
			        <li>{{obj.item}}</li>
			    </div>       
			    <div class='col-sm-3'>
			        <li>{{obj.quantidade}}</li>
			    </div>
			    <div class='col-sm-3'>
			        <li>{{obj.custo}}</li>
			    </div>
			    <div class='col-sm-2 text-center'>
	                <a href='{% url "compra:compraitemdetalhe" obj.id %}'>
	                   	<span title='Visualizar' class="glyphicon glyphicon glyphicon-zoom-in"></span>
	                </a>&nbsp;&nbsp;&nbsp;
	                {% if perms.compra.pode_administrar %}
			                <a href='{% url "compra:compraitemedita" obj.id %}'>
			                   	<span title='Editar' class="glyphicon glyphicon-pencil"></span>
			                </a>&nbsp;&nbsp;&nbsp;
			                <a href="javascript:func()" onclick="confirmacao('{% url "compra:compraitemapaga" obj.id %}')">
			                   	<span style="color:red" title='Excluir' class="glyphicon glyphicon-trash"></span>
			                </a>
	                {% endif %}
			    </div>
			    </ul>
		    </div>
	  	</div>
	{% endfor %}
	<hr>
	<div class='text-center'>
	<div class="pagination"> <!-- Paginação-->
	    <span class="step-links">
	        {% if listadeitens.has_previous %}
	            <a href="?{{ page_request_var }}={{ listadeitens.previous_page_number }}"><strong><< </strong></a>
	        {% endif %}

	        <span class="current">
	            {{ listadeitens.number }} / {{ listadeitens.paginator.num_pages }}
	        </span>

	        {% if listadeitens.has_next %}
	            <a href="?{{ page_request_var }}={{ listadeitens.next_page_number }}"><strong> >></strong></a>
	        {% endif %}
	    </span>
	</div>
	</div>
{% endblock %}
{% block jquery %}
	<script language="Javascript">
		function confirmacao(id) {
			var resposta = confirm("Deseja remover este item da compra ?");
   			if (resposta == true) {
      			window.location.href = id;
   			}
		}
	</script>
{% endblock %}