core/urls.py
from django.conf.urls import url, include

from .views	import usuario_detalhe, home

urlpatterns = [
   url(r'^home/', home, name='home'),
   url(r'^usuario/', usuario_detalhe, name='usuario'),
]

fiocruz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.urls import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^armazem/', include('armazem.urls', namespace='armazem')),
    url(r'^compra/', include('compra.urls', namespace='compra')),
    url(r'^fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    url(r'^item/', include('item.urls', namespace='item')),
    url(r'^requisicao/', include('requisicao.urls', namespace='requisicao')),
    url(r'^usuario/', include('core.urls', namespace='core')),
    url(r'^login/',views.login, {'template_name':'login.html'}, name='login'),
    url(r'^logout/',views.logout_then_login, { 'login_url': '/login/'}, name='logout')
]

item/urls.py
from django.conf.urls import url, include

from .views	import item_cria, item_lista, item_detalhe, item_edita, item_apaga
	

urlpatterns = [
    url(r'^$', item_lista, name='lista'),
    url(r'^cria/$', item_cria, name='cria'),
    url(r'^apaga/(?P<id>\d+)/$', item_apaga, name='apaga'),
    url(r'^detalhe/(?P<id>\d+)/$', item_detalhe, name='detalhe'),
    url(r'^edita/(?P<id>\d+)/$', item_edita, name='edita')
]

core/models.py
from django.db import models


class Estado(models.Model):

	sigla		= models.CharField(max_length=2,null=False)
	nome		= models.CharField(max_length=20,null=False)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)

	class Meta:
		ordering = ['sigla']

	def __unicode__(self):
		return self.nome

	def __str__(self):
		return self.nome

class Municipio(models.Model):

	nome		= models.CharField(max_length=40)
	estado      = models.ForeignKey(Estado)
	criado	 	= models.DateTimeField(auto_now=False,auto_now_add=True)
	atualizado 	= models.DateTimeField(auto_now=True,auto_now_add=False)

	class Meta:
		ordering = ['nome']
		
	def __unicode__(self):
		return self.nome

	def __str__(self):
		return self.nome

# Estado(sigla='AC',nome='Acre').save()
# Estado(sigla='AL',nome='Alagoas').save()
# Estado(sigla='AP',nome='Amapá').save()
# Estado(sigla='AM',nome='Amazonas').save()
# Estado(sigla='BA',nome='Bahia').save()
# Estado(sigla='CE',nome='Ceara').save()
# Estado(sigla='DF',nome='Distrito Federal').save()
# Estado(sigla='GO',nome='Goiás').save()
# Estado(sigla='MA',nome='Maranhão').save()
# Estado(sigla='MT',nome='Mato Grosso').save()
# Estado(sigla='MS',nome='Mato Grosso do Sul').save()
# Estado(sigla='MG',nome='Minas Gerais').save()
# Estado(sigla='PA',nome='Pará').save()
# Estado(sigla='PB',nome='Paraíba').save()
# Estado(sigla='PR',nome='Paraná').save()
# Estado(sigla='PE',nome='Pernambuco').save()
# Estado(sigla='PI',nome='Piauí').save()
# Estado(sigla='RJ',nome='Rio de Janeiro').save()
# Estado(sigla='RN',nome='Rio Grande do Norte').save()
# Estado(sigla='RS',nome='Rio Grande do Sul').save()
# Estado(sigla='RO',nome='Rondônia').save()
# Estado(sigla='RR',nome='Roraima').save()
# Estado(sigla='SC',nome='Santa Catarina').save()
# Estado(sigla='SP',nome='São Paulo').save()
# Estado(sigla='SE',nome='Sergipe').save()
# Estado(sigla='TO',nome='Tocantins').save()

# e = Estado(sigla='MS',nome='Mato Grosso do Sul').save()
# Estado(sigla='AC',nome='Acre').save()

core/forms.py
from django import forms

class UsuarioForm(forms.Form):

	password = forms.CharField(required=True)

core/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Sum,Q 
from .forms import  UsuarioForm
from compra.models import Compra,ItemCompra
from datetime import date

@login_required
def home(request):
	totais = []
	for indice in range(13):
		queryset = ItemCompra.objects.filter(compra__data_pagamento__month=indice).filter(criado__year=date.today().year)
		queryset = queryset.aggregate(Sum('custo'))
		totais.append(queryset)
	totais.remove({'custo__sum': None}) # Ajuste para bug da logica, estudar correção
	context = { 'totais': totais }
	return render(request,'home.html', context)

@login_required
def usuario_detalhe(request):
	if request.method == 'POST':
		form = UsuarioForm(request.POST or None)
		if form.is_valid():
			instance = request.user
			instance.set_password(form.data['password'])
			instance.save()
			update_session_auth_hash(request, request.user)
			messages.success(request,' Senha foi alterada, e necessario um novo login.')
	return render(request,'usuario.html')

core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang='pt-br'>
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FIOCRUZ Regional MS</title>
	<link rel="shortcut icon" href="/static/images/favico.ico"/>
	<link rel='stylesheet' href='/static/css/bootstrap.min.css'>
	<link rel='stylesheet' href='/static/css/fiocruz.css'>
</head>
<body style="background-color:#cbcbcb">
	<div>

		{% include 'menu.html' %}
		
		{% include 'message.html' %}

		<div class='row'>
			<div class='col-sm-1'></div>
			<div class='col-sm-10'>

			{% block header %}
			{% endblock %}

			{% block main %}
			{% endblock %}

			{% block footer %}
				{% include 'footer.html' %}
			{% endblock %}

			</div>
			<div class='col-sm-1'></div>
			<h3 id='texto'></h3>
		</div>
		<div>
			<script src="/static/js/jquery.min.2.2.4.js"></script>
			<script src='/static/js/bootstrap.min.js'></script>
			<script src='/static/js/jquery.flot.js'></script>
			<script src='/static/js/jquery.flot.categories.js'></script>
			<script src="/static/js/RGraph/libraries/RGraph.common.core.js"></script>
			<script src="/static/js/RGraph/libraries/RGraph.bar.js"></script>
			{% block jquery %}
			{% endblock %}
		</div>
	</div>
</body>
</html>

core/templates/footer.html
  <!-- Fixed navbar bottom -->
  <div class='row'>
  	<div class='col-sm-2'></div>
	   	<div class='col-sm-8'>
  		</div>
	<div class='col-sm-2'></div>
</div>

core/templates/footer_login.html
  <!-- Fixed navbar bottom -->
  <div class='row'>
  	<div class='col-sm-2'></div>
	   	<div class='col-sm-8'>
	   			<br>
	   			<h5 class='text-center text-muted'>Build 87</h5>
  		</div>
	<div class='col-sm-2'></div>
</div>

core/templates/header.html
<div class='row'>
  <div class='col-sm-1'></div>
    <div class='col-sm-10'>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="#">FIOCRUZ</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li class="active"><a href="#">Início</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Almoxarifado<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'armazem:list' %}">Armazém</a></li>
                  <li><a href="#">ítens</a></li>
                  <li class="divider"></li>
                  <li><a href="#">Requsição</a></li>
                </ul>
              </li>
              <li><a href="#">Menu 2</a></li>
              <li><a href="#">Menu 3</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="#"><span class="glyphicon glyphicon-user"></span> Usuário</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Entrar</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  <div class='col-sm-1'></div>
</div>

core/templates/home.html
{% extends 'base.html' %}
{% block header %}
<div class="row"> 
    <div class="col-sm-6">
        <h4>Quadro de Avisos</h4>
        <hr>
    </div>   
    <div class="col-sm-1">
    </div>
    <div class="col-sm-5">
        <h4>Indicadores</h4>
        <hr>
    </div>  
</div> 
{% endblock %}
{% block main %}
<div class="row"> 
    <div class="col-sm-6">
      <p>23-09-2016 - <i>Incluído o modulo de requisições.</i><p>
      <p>22-09-2016 - <i>Inplementado o demostrativo gráfico de compras.</i></p>
	  <p>30-08-2016 - <i>Inplementado base de compras.</i></p>
	  <p>11-08-2016 - <i>Implementado integridade de eventos vinculados.</i></p>
	  <p>29-07-2016 - <i>Implantado o sistema no ambiente Apache 2.4 por SSL.</i></p>
	  <p>20-07-2016 - <i>Migração da base de dados para o MySql Server 5.7.</i></p>
	</div>
	<div class="col-sm-1">
	</div>
	<div class="col-sm-5">
	  	<canvas id="cvs" width="450" height="250">
    			[Este navegador não suporta o CANVAS]
		</canvas>
	</div> 
</div>
{% endblock %}
{% block jquery %}
<script>
    window.onload = function ()
    {
        var bar = new RGraph.Bar({
            id: 'cvs',
            data: [
            		{% for mes in totais %}
	            		{% if mes.custo__sum %} 
	            			"{{mes.custo__sum}}", 
	            		{% else %} 
	            			0,
	            		{% endif %}

            		{% endfor %}
            		],
            options: {
            	unitsPost: ' R$',
                textAccessible: true,
                gutterTop: 35,
                gutterLeft: 35,
                title: 'Pagamentos',
                labels: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
            }
        }).draw();
    };
</script>
{% endblock %}

core/templates/login.html
<!DOCTYPE html>
<html lang='pt-br'>
    <head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>FIOCRUZ Regional MS</title>
	<link rel="shortcut icon" href="/static/images/favico.ico"/>
	<link rel='stylesheet' href='/static/css/bootstrap.min.css'>
	<link rel='stylesheet' href='/static/css/fiocruz.css'>
	<link rel='stylesheet' href='/static/css/login.css'>

</head>
<body style="background-color:#cbcbcb">
<div class="container">
    <div class="content">
      <div class="row">
        <div class="login-form text-center">
          <form name="enviando" id="enviando" action="{% url 'login' %}" method="post">
          {% csrf_token %}
            <fieldset>
            	<h3>FIOCRUZ</h3>
          		<h4>Mato Grosso do Sul</h4>
          		<div class="clearfix">
                	<input class="form-group input-sm" type="text" id="id_username" name="username" class="form_control" placeholder="Usuário" required autofocus>
              	</div>
	            <div class="clearfix">
	                <input class="form-group input-sm" type="password" id="id_password" name="password" class="form_control" placeholder="Senha" required>
	              </div>
	            <div class="clearfix">
	            {% if form.errors %}
	            	<br>
					<div class="alert alert-default">
						<button type="btn-sm" class='close'></button><span class="glyphicon glyphicon-info-sign"></span> Ops, não foi possível.
					</div>
				{% endif %}
				</div>
              	<div> 
              	<button type="submit">Button de envio escondido pelo CSS.</button>
              	</div> <!--
              	<input type="hidden" name="next" value="{{ lista }}"> <!-- Encaminha para página -->
            </fieldset>
          </form>
        </div>
      </div>
    </div>
</div> <!-- /container -->
{% block footer %}
	{% include 'footer_login.html' %}
{% endblock %}
<div>
	<script src="/static/js/jquery.min.2.2.4.js"></script>
	<script src='/static/js/bootstrap.min.js'></script>
</div>
</body>
</html>

core/templates/menu.html
<div class='row'>
  <div class='col-sm-1'></div>
    <div class='col-sm-10'>
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>                        
            </button>
            <a class="navbar-brand" href="#">FIOCRUZ</a>
          </div>
          <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
              <li><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Início</a></li>
              <li><a href="#"><span class="glyphicon glyphicon-th-list"></span> Qualidade</a></li>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#"><span class="glyphicon glyphicon-th-list"></span> Materiais</a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'requisicao:lista' %}"><span class="glyphicon glyphicon-inbox"></span> Requsições</a></li>  
                  <li class="divider"></li>              
                  <li><a href="{% url 'armazem:lista' %}"><span class="glyphicon glyphicon-list-alt"></span>  Armazens</a></li>
                  <li><a href="{% url 'compra:lista' %}"><span class="glyphicon glyphicon-list-alt"></span> Compras</a></li>                  
                  <li><a href="{% url 'fornecedor:lista' %}"><span class="glyphicon glyphicon-list-alt"></span> Fornecedores</a></li>
                  <li><a href="{% url 'item:lista' %}"><span class="glyphicon glyphicon-list-alt"></span> Ítens</a></li>
                </ul>
              </li>
              <li><a href="#"><span class="glyphicon glyphicon-th-list"></span> Patrimônio</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'core:usuario' %}"><span class="glyphicon glyphicon-user"></span>&nbsp;&nbsp;{{ request.user.first_name }}
              </a></li>
              <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;&nbsp;Sair</a></li>
            </ul>
          </div>
        </div>
      </nav>
    </div>
  <div class='col-sm-1'></div>
</div>

core/templates/message.html
<div class='row'>
<div class='col-sm-2'>
</div>
<div class='col-sm-8'>
	{% if messages %}
	    <ul class="messages text-left"> 
		    {% for message in messages %}
				{% if message.tags == 'success' %}
					<div class="alert alert-success alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
	  					<span class="glyphicon glyphicon-ok-sign"></span>{{ message }}             
		            </div>
			    {% endif %}
			    {% if message.tags == 'info' %}
		          	<div class="alert alert-info alert-dismissible" role="alert">
	  					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  						<span aria-hidden="true">&times;</span>
	  					</button>
	  					<span class="glyphicon glyphicon-info-sign"></span>{{ message }}
		            </div>
			    {% endif %}
			    {% if message.tags == 'warning' %}
		            <div class="alert alert-warning alert-dismissible" role="alert">
						<button type="button" class="close" data-dismiss="alert" aria-label="Close">
							<span aria-hidden="true">&times;</span>
						</button>
	  					<span class="glyphicon glyphicon-exclamation-sign"></span>{{ message }}
		            </div>
			    {% endif %}
			    {% if message.tags == 'error' %}
			        <div class="alert alert-danger alert-dismissible" role="alert">
	  					<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	  							<span aria-hidden="true">&times;</span>
	  					</button>
						<span class="glyphicon glyphicon-remove-sign"></span>{{ message }
		            </div>
		        {% endif %}
		    {% endfor %}
		</ul>
	{% endif %}
</div>
<div class='col-sm-2'></div>
</div>

core/templates/usuario.html
{% extends 'base.html' %}
{% block header %}

{% endblock %}
{% block main %}
<form method='POST' action=''>{% csrf_token %}
<div class="row"> <!-- Cabecalho da página de Listas -->
    <div class="col-sm-3">
        <h4 class='text-muted'>{{ request.user.get_full_name }}</h4>
    </div>   
    <div class="col-sm-7">
    </div>   
    <div class="col-sm-1 text-center">
        <button title='Alterar ' class='btn btn-primary btn-sm' type='submit'>
          <span class="glyphicon glyphicon-check"></span>
        </button>
    </div>
    <div class="col-sm-1 text-center">
    </div>
</div> 
<hr>
  <div class="row col-sm-12"> <!-- Ítens da página de detalhes Linha 1-->
  	<div class="row">
    		<div class="col-sm-4">
      		<p class='text-muted'><strong>E-mail</strong></p>
      		<p class='text-muted'>{{ request.user.email }}</p>
    		</div>
    		<div class="col-sm-4">
      		<p class='text-muted'><strong>Perfil</strong></p>
      		<p class='text-muted'>
          {% if request.user.is_superuser %}
              Administrador do sistema
          {% endif %}
          {% if perms.armazem.pode_administrar or perms.compra.pode_administrar or perms.compra.pode_administrar or perms.fornecedor.pode_administrar or perms.item.pode_administrar or perms.requisicao.pode_administrar %}
                      Usuário master
          {% else %}
                      Usuário do sistema
          {% endif %}
          </p>
    		</div>
        <div class="col-sm-4">
        <p class='text-muted'><strong>Ativo</strong></p>
          {% if request.user.is_active %}
            <p class='text-muted'><strong class='text-success'>Sim</strong></p>
          {% else %}
            <p class='text-muted'><strong class='text-danger'>Não</strong></p>
          {% endif %}
        </div>
  	</div>
  </div>

  <div class="row col-sm-12"> <!-- Ítens da página de detalhes linha 2-->
    <div class="row">
        <div class="col-sm-4">
          <p class='text-muted'><strong>Último acesso </strong></p>
          <p class='text-muted'>{{request.user.last_login}}</p>
        </div>
        <div class="col-sm-4">
          <p class='text-muted'><strong>Criado</strong></p>
          <p class='text-muted'>{{request.user.date_joined}}</p>
        </div>
        <div class="col-sm-4">
          <p><strong>Nova senha</strong></p>
          <p>
            <input class="input-sm" type="password" id="id_password" name="password" class="form_control" placeholder="Nova Senha" required>
          </p>
        </div>
    </div>
  </div>
</form>
{% endblock %}